import type { Post } from '../types';

export const SAMPLE_POSTS: Omit<Post, 'id' | 'user_id'>[] = [
  {
    title: '3 razões pelas quais marcas autênticas vendem mais',
    content: 'Autenticidade não é apenas uma tendência — é a base do relacionamento moderno entre marcas e pessoas. 🔥\n\n1. As pessoas compram de quem confiam\n2. Histórias reais criam conexões profundas\n3. Consistência constrói autoridade\n\nQual é a história real por trás da sua marca? Compartilha nos comentários 👇',
    platform: 'Instagram',
    type: 'Carrossel',
    archetype: 'O Herói',
    status: 'published',
    likes: 234,
    engagement: '4.8%',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#branding', '#autenticidade', '#marketing'],
    tip: 'Publique às 19h para maior engajamento',
  },
  {
    title: 'Como o arquétipo da sua marca define o conteúdo que você cria',
    content: 'Você sabia que marcas com arquétipo definido têm até 3x mais engajamento nas redes sociais?\n\nO arquétipo é a personalidade profunda da sua marca — é ele que guia o tom de voz, as cores, o tipo de conteúdo e como você se conecta com seu público.\n\nSe você ainda não sabe qual é o seu, chegou a hora de descobrir. 👇',
    platform: 'LinkedIn',
    type: 'Artigo',
    archetype: 'O Sábio',
    status: 'published',
    likes: 187,
    engagement: '6.2%',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#arquétipos', '#branding', '#marketingdigital'],
    tip: 'Adicione um link para seu site no primeiro comentário',
  },
  {
    title: 'Thread: Tudo que aprendi sobre posicionamento em 6 meses',
    content: '🧵 Thread: Tudo que aprendi sobre posicionamento de marca em 6 meses de teste (e alguns erros caros)\n\n1/ Posicionamento não é sobre o que você vende — é sobre quem você é para o seu cliente.\n\n2/ Marcas genéricas competem por preço. Marcas posicionadas competem por identidade.\n\n3/ Seu arquétipo de marca deve aparecer em TUDO: copy, visual, atendimento, embalagem.\n\n4/ Quando você encontra seu posicionamento certo, o "não" dos clientes errados vira combustível.',
    platform: 'Twitter/X',
    type: 'Thread',
    archetype: 'O Fora-da-Lei',
    status: 'published',
    likes: 512,
    engagement: '8.1%',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#marketing', '#branding', '#empreendedorismo'],
    tip: 'Threads funcionam melhor quando postados de manhã',
  },
  {
    title: 'O segredo das marcas que as pessoas amam',
    content: 'Você já parou para pensar por que algumas marcas criam verdadeiros fãs enquanto outras ficam no esquecimento? 💭\n\nA resposta está nos arquétipos de Carl Jung — uma metodologia usada pelas maiores marcas do mundo para criar conexões emocionais genuínas.\n\nNeste vídeo, vou te mostrar como descobrir o arquétipo da sua marca e usar isso para criar conteúdo que ressoa de verdade com o seu público.',
    platform: 'YouTube',
    type: 'Vídeo',
    archetype: 'O Mago',
    status: 'published',
    likes: 892,
    engagement: '12.3%',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#branding', '#jung', '#marketing'],
    tip: 'Use thumbnail com rosto para mais cliques',
  },
  {
    title: 'Bastidores: como criamos nossa identidade de marca',
    content: '🎬 Mostrando os bastidores da criação da nossa identidade de marca!\n\nDo rascunho no papel até o resultado final — cada decisão foi guiada pelo nosso arquétipo: O Criador.\n\nAcredito que marcas honestas mostram seu processo. Isso cria conexão real. ✨\n\nMe conta: você mostra os bastidores do seu negócio?',
    platform: 'Instagram',
    type: 'Reels',
    archetype: 'O Criador',
    status: 'published',
    likes: 1203,
    engagement: '9.7%',
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#bastidores', '#branding', '#criatividade'],
    tip: 'Reels com música trending têm mais alcance',
  },
  {
    title: 'Por que sua marca precisa de um arquétipo (não apenas um logo)',
    content: 'Um logo é visual. Um arquétipo é alma.\n\nMuitas marcas investem fortunas em identidade visual mas esquecem a identidade de marca — a personalidade profunda que guia todas as decisões de comunicação.\n\nO resultado? Conteúdo inconsistente, público confuso e vendas que não chegam ao potencial.\n\nVeja como definir o arquétipo da sua marca em 3 passos:\n👉 1. Entenda seus valores fundamentais\n👉 2. Conheça profundamente seu cliente ideal\n👉 3. Identifique as emoções que você quer provocar',
    platform: 'LinkedIn',
    type: 'Post',
    archetype: 'O Governante',
    status: 'published',
    likes: 345,
    engagement: '5.4%',
    published_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#branding', '#liderança', '#marketing'],
    tip: 'Posts longos no LinkedIn têm melhor alcance orgânico',
  },
  {
    title: 'Conteúdo que converte: a fórmula dos arquétipos',
    content: '✅ Conteúdo que converte = Arquétipo correto + Plataforma certa + Timing perfeito\n\nÉ assim que as marcas mais poderosas do mundo criam conteúdo que transforma seguidores em clientes.\n\nSalva esse post! 📌',
    platform: 'Instagram',
    type: 'Post',
    archetype: 'O Herói',
    status: 'published',
    likes: 678,
    engagement: '7.2%',
    published_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#conteudo', '#conversao', '#marketing'],
    tip: 'Use o recurso "Salvar" como call-to-action',
  },
  {
    title: 'Guia completo de tom de voz para marcas',
    content: 'Tom de voz não é sobre soar bonito. É sobre soar verdadeiro.\n\nEste guia vai te ajudar a definir como sua marca se comunica em cada situação — das redes sociais ao atendimento ao cliente.\n\nEm construção... compartilhe com quem precisa! 🛠️',
    platform: 'Twitter/X',
    type: 'Post',
    archetype: 'O Sábio',
    status: 'draft',
    likes: 0,
    engagement: '-',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#tomdevoz', '#branding', '#comunicacao'],
    tip: 'Adicione exemplos concretos antes de publicar',
  },
  {
    title: '5 erros de branding que destroem marcas promissoras',
    content: 'Vídeo em produção: os 5 erros mais comuns que vejo marcas cometendo e como evitá-los antes que seja tarde demais.\n\nEsperamos você na próxima semana! 🎬',
    platform: 'YouTube',
    type: 'Vídeo',
    archetype: 'O Cuidador',
    status: 'draft',
    likes: 0,
    engagement: '-',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#branding', '#erros', '#marcas'],
    tip: 'Grave um hook forte nos primeiros 5 segundos',
  },
  {
    title: 'Workshop: Descobrindo o arquétipo da sua marca',
    content: '🎯 Workshop ao vivo: Como descobrir o arquétipo da sua marca em 2 horas\n\nVamos trabalhar juntos para:\n✅ Mapear os valores da sua marca\n✅ Identificar seu arquétipo principal\n✅ Criar diretrizes de conteúdo\n✅ Desenvolver seu tom de voz\n\nInscrições abertas na bio! 🔗',
    platform: 'Instagram',
    type: 'Story',
    archetype: 'O Explorador',
    status: 'draft',
    likes: 0,
    engagement: '-',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#workshop', '#branding', '#arquétipos'],
    tip: 'Stories com enquete aumentam interação em 3x',
  },
  {
    title: 'Lançamento: Guia definitivo de arquétipos de marca',
    content: '🚀 Em breve: O Guia Definitivo dos 12 Arquétipos de Marca\n\nTudo que você precisa saber para construir uma marca com personalidade forte, conteúdo consistente e conexão genuína com seu público.\n\nFique de olho — lançamento na próxima segunda! 👀',
    platform: 'Instagram',
    type: 'Post',
    archetype: 'O Criador',
    status: 'scheduled',
    likes: 0,
    engagement: '-',
    scheduled_for: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#lancamento', '#guia', '#branding'],
    tip: 'Programe para segunda às 9h para maior alcance',
  },
  {
    title: 'Série: Arquétipos na prática — O Herói',
    content: '⚡ Série Arquétipos na Prática — Episódio 1: O Herói\n\nMarcas com arquétipo Herói inspiram superação e ação. Exemplos: Nike, Red Bull, Adidas.\n\nEste episódio cobre:\n• Como o Herói se comunica\n• Tipos de conteúdo que funcionam\n• Tom de voz e vocabulário\n• Cases de sucesso\n\nPublicação na quinta-feira! 🎯',
    platform: 'LinkedIn',
    type: 'Artigo',
    archetype: 'O Herói',
    status: 'scheduled',
    likes: 0,
    engagement: '-',
    scheduled_for: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    hashtags: ['#heroi', '#arquétipos', '#branding'],
    tip: 'Artigos com imagem têm 2x mais visualizações',
  },
];
